[workspace]
members = ["crates/engine"]
resolver = "3"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
cast_possible_truncation = "allow"
module_name_repetitions = "allow"
